### PR TITLE
install: use --capability with zypper {install,remove}

### PR DESCRIPTION
**Pull request by smithfarm**
Otherwise we pick up python-ceph 0.80.9 from the distro repo instead of
a newer python-ceph-compat from the test repo.

References: https://bugzilla.opensuse.org/show_bug.cgi?id=997751
Signed-off-by: `Nathan Cutler <ncutler@suse.com>`

### CODE REVIEW

**Comment by smithfarm** [comment]
@rjfd Please review.

**Comment by smithfarm** [comment]
Obviously, this will need testing (hence the DNM).

**Comment by rjfd** [comment]
LGTM

**Comment by smithfarm** [comment]
`cw -v ceph-qa-suite --teuthology-git-url http://github.com/SUSE/teuthology --teuthology-branch wip-openstack-zypper-capabilities --suite-branch wip-16516 --ceph jewel --suite rados/basic --subset 0/2000`

**running** http://158.69.85.90:8081/ubuntu-2016-09-14_11:04:25-rados:basic-jewel---basic-openstack/

**Comment by smithfarm** [comment]
@dachary The failure is http://tracker.ceph.com/issues/16516 so unrelated I think.

**Comment by dachary** [comment]
<pre>
Reviewed-by: Loic Dachary &lt;ldachary@redhat.com>
</pre>

**Comment by smithfarm** [comment]
@dachary I will run a test or two on with openSUSE_42.1.yaml

**Comment by smithfarm** [comment]
A very similar test with `distros/all/opensuse_42.1.yaml`:

**running** http://158.69.85.90:8081/ubuntu-2016-09-15_13:31:49-rados:basic-ses3---basic-openstack/

**Comment by smithfarm** [comment]
@dachary I did a fair amount of testing and debugging on this yesterday. There are still some issues testing jewel on openSUSE Leap 42.1 VMs using teuthology-openstack, but none of them are related to this patch. In the end I managed to get this: http://158.69.85.90:8081/ubuntu-2016-09-16_05:30:50-rados:basic-ses3---basic-openstack/ (7 successful jobs, 3 failures - all failures unrelated to this PR).

**Pull request merged**
