### PR TITLE
misc: ignore some unusable block devices

### PR DESCRIPTION
**Pull request by robbat2**
If a block device is read-only, or is a cloud-init datasource, we should
not change the content on it!

This change detects most documented datasources as of 2015/12/10 from
http://cloudinit.readthedocs.org/en/latest/topics/datasources.html

It cannot detect datasources that are only detectable based on files on
volume (eg config-drive v1)

Signed-off-by: Robin H. Johnson <robin.johnson@dreamhost.com>

### CODE REVIEW

**Comment by dachary** [comment]
<pre>
  File "/home/loic/software/ceph/teuthology/teuthology/misc.py", line 878
    and dev_blkid_data[dev]['TYPE'] is 'iso9660':
                                                ^
SyntaxError: invalid syntax
</pre>

**Comment by dachary** [comment]
@robbat2 you can make a pull request against ceph/teuthology instead, I'll pick from it (and it will run tox to catch these).

**Comment by robbat2** [comment]
I caught that one, it was me missing a ) on the previous line mostly.

I made the PR against dachary/teuthology/openstack because ceph/teuthology/wip-openstack seems to be quite far behind your  dachary/teuthology/openstack branch

**Comment by dachary** [comment]
@robbat2 dachary/teuthology/openstack is ~20 commits ahead of master currently. I make sure @zmc pull request pipeline is never empty to ensure it won't diverge too much. I'll delete wip-openstack to avoid confusion in the future.

**Comment by dachary** [comment]
@robbat2 and since this pull request is only indirectly related to openstack, there won't be merge conflicts.

**Pull request closed without merging**
